### ISSUE TITLE
Yellow banner disappear

### ISSUE THREAD

**Issue by sheymann** [Linkurious/demo.linkurio.us#6]
https://github.com/Linkurious/website/issues/63

**Comment by sheymann** [comment]
@davidrapin can you update index.html on the demo server plz? I cannot remember the password.

**Comment by davidrapin** [comment]
@sheymann Please describe the issue

**Comment by sheymann** [comment]
I cannot access 178.32.67.1 because I've lot my password. Please remplace index.html with this:
https://github.com/Linkurious/demo.linkurio.us/blob/master/index.html

**Comment by davidrapin** [comment]
Done

**Comment by davidrapin** [comment]
process for next time:
```bash
ssh linkurious@crunchbase.linkurio.us
cd /home/linkurious/demo.linkurio.us
git pull
```
